name: binkap_parsely
description: " A Flutter package for parsing links, emails, @mentions, hashtags, and phone numbers from text.  Mask extracted elements with custom patterns and add tappable click behavior for seamless interactions"
version: 0.0.1
homepage: "https://binkap.com"

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
